### ISSUE TITLE
Image Streamer Client cannot be created with the OneView environment variables

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#183] opened 2017-02-17 17:56 UTC
### Scenario/Intent
I want to create my Image Streamer client only using the environment variables:
  1. `ENV['ONEVIEWSDK_URL']`, `ENV['ONEVIEWSDK_USER']`, `ENV['ONEVIEWSDK_PASSWORD']` and  `ENV['I3S_URL']`
  2.  `ENV['ONEVIEWSDK_TOKEN']` and  `ENV['I3S_URL']`
but I can't, since it won't parse the OneView environment variables to gather the token.

### Environment Details
 - **OneView SDK Version:** 4.0.0
 - **OneView Client API Version:** API300
 - **Ruby Version:** 2.2.6
 - **Platform:** N/A

### Steps to Reproduce
1. With OneView User/Password
    1. Set the environment variables: `ENV['ONEVIEWSDK_URL']`, `ENV['ONEVIEWSDK_USER']`,   `ENV['ONEVIEWSDK_PASSWORD']` and  `ENV['I3S_URL']` to valid values.
    2. Create the `OneviewSDK::ImageStreamer::Client.new` relying on the Environment variables.
2. With OneView Token
    1. Set the environment variables: `ENV['ONEVIEWSDK_TOKEN']` and  `ENV['I3S_URL']` to valid values.
    2. Create the `OneviewSDK::ImageStreamer::Client.new` relying on the Environment variables.

### Expected Result
The Image Streamer client should be created succesfully with the environment variables values.

### Actual Result
It fails:
```
OneviewSDK::InvalidClient:
  Must set token option
```

**Comment by aalexmonteiro** [comment] 2017-02-17 18:05
@tmiotto , Could not create, because the environment variable is I3S_TOKEN. But now I see that maybe not need this environment variable, and it may just be ONEVIEWSDK_TOKEN.

**Comment by jsmartt** [comment] 2017-02-17 18:30
👍 Yeah, I think we only need 1 env variable for a token.

**Comment by aalexmonteiro** [comment] 2017-02-17 18:56
So in this case this would not be a bug, but an improvement. You agree? Correct me if I'm wrong. Please. :)

**Comment by jsmartt** [comment] 2017-02-17 21:16
Yeah. This is where that warning saying that I3S is experimental and subject to change at this point. We can easily change pretty much anything still. I'd label it an improvement and/or unexpected behavior.

**Comment by tmiotto** [comment] 2017-02-20 20:11
Regarding number 2 okay, it may be an improvement if we would just want to remove the I3S Token.

But regarding number 1, if I'm using the ENV variables user and password for OneView why would I now have to do the login and get the token to use in Image Streamer?

**Comment by aalexmonteiro** [comment] 2017-02-20 21:05
@tmiotto , I think I understood your question. With the change made to the i3s login mode that was recently merged into the master, this is no longer necessary. But this case, the user would have to create the i3s_client instance with the method new_i3s_client of oneview client.

So, we can thought in a solution when the user wants uses the enviroments variables with user and password. Could be something like:

```ruby
# on initialize of i3s client
if ENV['ONEVIEWSDK_USER'] && NV['ONEVIEWSDK_PASSWORD'] && ENV['I3S_URL']
   ov_client = Oneview::Client.new
   @token = ov_client.token
end
```

Let me know what your thoughts about this.

**Comment by tmiotto** [comment] 2017-02-21 12:53
@aalexmonteiro  I see...

Well then we would have:
```ruby
ov_client = OneviewSDK::Client.new # Relying on ONEVIEWSDK ENV
i3s_client = ov_client.new_image_streamer_client # Relying on I3S ENV
```
as the expected use case.

The one I was talking is:
```ruby
i3s_client = OneviewSDK::ImageStreamer::Client.new # Relying on ONEVIEWSDK and I3S ENV
```
that I'm okay not implementing considering the expected and unexpected use cases would be thoroughly documented in the README, so we won't have users complaining that some other ways to create the client are not working when we are expecting them to not work.

**Closed** 2017-02-22 21:11 UTC
Labels: API300, bug/bug-fix, image_streamer
